// Database
// eslint-disable-next-line no-restricted-imports -- TODO(core-migration): export.demo-page
import db from '../../../database';
// Shared SVG utility
import { flattenSvgUseRefs } from '../iconfontGenerator';
// Templates — inlined at build time via Vite ?raw import
// No runtime file I/O needed, works in both dev and production
import htmlTemplate from '../../../resources/iconDocs/indexTemplate.html?raw';

import jsHead from '../../../resources/iconDocs/iconfontTemplate(symbol).head.txt?raw';
import jsTail from '../../../resources/iconDocs/iconfontTemplate(symbol).tail.txt?raw';

// App icon — imported as URL by Vite, pre-converted to base64 data URI
import appIconUrl from '../../../resources/imgs/icon.png';

// Pre-cache icon as base64 data URI at module load so it embeds in exported HTML
let _appIconDataUri = appIconUrl; // fallback to Vite URL
const _iconImg = new Image();
_iconImg.onload = function () {
  try {
    const c = document.createElement('canvas');
    c.width = _iconImg.naturalWidth;
    c.height = _iconImg.naturalHeight;
    c.getContext('2d')!.drawImage(_iconImg, 0, 0);
    _appIconDataUri = c.toDataURL('image/png');
  } catch (_) {
    /* keep fallback */
  }
};
_iconImg.src = appIconUrl;

// i18n
import i18n from 'i18next';

// ---------------------------------------------------------------------------
// Type definitions
// ---------------------------------------------------------------------------

/** Group data passed to demo page generators */
interface DemoGroupData {
  id: string;
  groupName: string;
  [key: string]: any;
}

/** Icon data passed to demo page generators */
interface DemoIconData {
  iconCode: string;
  iconName: string;
  iconContent: string;
  [key: string]: any;
}

// ---------------------------------------------------------------------------
// Demo page UI strings — keyed by language
// ---------------------------------------------------------------------------
const DEMO_STRINGS: Record<string, Record<string, string>> = {
  en: {
    pageTitle: 'Icon Reference',
    searchPlaceholder: 'Search icons...',
    iconCount: '{n} icons',
    allGroups: 'All',
    noIcons: 'No icons in this group',
    copyCode: 'Copy',
    downloadSvg: 'SVG',
    toastCopied: 'Copied: {code}',
    toastDownloaded: 'Downloaded: {name}.svg',
    usageTitle: 'USAGE',
    unicodeDesc:
      'Unicode references use the character code point to display icons. Suitable for all platforms.',
    unicodeStep1: 'Step 1: Declare the font',
    unicodeStep2: 'Step 2: Define the base class',
    unicodeStep3: 'Step 3: Use via HTML entity',
    fontclassDesc: 'Font Class uses CSS classes for a more semantic and readable API.',
    fontclassStep1: 'Step 1: Include the stylesheet',
    fontclassStep2: 'Step 2: Use the class name',
    symbolDesc: 'SVG Symbol uses inline SVG sprites for multi-color and scalable icons.',
    symbolStep1: 'Step 1: Include the JS sprite',
    symbolStep2: 'Step 2: Add base styles',
    symbolStep3: 'Step 3: Reference by ID',
    wikiLinkText: 'Learn more in Bobcorn Wiki',
    footerGenerated: 'Generated by Bobcorn',
    footerWiki: 'Wiki',
  },
  'zh-CN': {
    pageTitle: '图标一览',
    searchPlaceholder: '搜索图标...',
    iconCount: '{n} 个图标',
    allGroups: '全部',
    noIcons: '该分类下暂无图标',
    copyCode: '复制',
    downloadSvg: 'SVG',
    toastCopied: '已复制: {code}',
    toastDownloaded: '已下载: {name}.svg',
    usageLabel: '开发参考',
    usageTitle: '在项目中使用你的图标',
    usageDesc: '三种集成方式——选择适合你技术栈的方案。所有文件已包含在本次导出中。',
    unicodeStep1: '第一步 — 声明字体',
    unicodeStep2: '第二步 — 定义基础类名',
    unicodeStep3: '第三步 — 通过 HTML 实体使用',
    fontclassStep1: '第一步 — 引入样式表',
    fontclassStep2: '第二步 — 使用类名',
    symbolStep1: '第一步 — 引入 JS 精灵图',
    symbolStep2: '第二步 — 添加基础样式',
    symbolStep3: '第三步 — 通过 ID 引用',
    wikiLinkText: '在 Bobcorn Wiki 了解更多',
    footerGenerated: '由 Bobcorn 生成',
  },
  ja: {
    pageTitle: 'アイコン一覧',
    searchPlaceholder: 'アイコンを検索...',
    iconCount: '{n} 個のアイコン',
    allGroups: 'すべて',
    noIcons: 'このグループにはアイコンがありません',
    copyCode: 'コピー',
    downloadSvg: 'SVG',
    toastCopied: 'コピー済み: {code}',
    toastDownloaded: 'ダウンロード済み: {name}.svg',
    usageLabel: '開発リファレンス',
    usageTitle: 'プロジェクトでアイコンを使う',
    usageDesc: '3つの統合方法から選べます。すべてのファイルはエクスポートに含まれています。',
    unicodeStep1: 'ステップ1 — フォントを宣言',
    unicodeStep2: 'ステップ2 — 基本クラスを定義',
    unicodeStep3: 'ステップ3 — HTMLエンティティで使用',
    fontclassStep1: 'ステップ1 — スタイルシートを読み込み',
    fontclassStep2: 'ステップ2 — クラス名を使用',
    symbolStep1: 'ステップ1 — JSスプライトを読み込み',
    symbolStep2: 'ステップ2 — 基本スタイルを追加',
    symbolStep3: 'ステップ3 — IDで参照',
    wikiLinkText: 'Bobcorn Wiki で詳しく',
    footerGenerated: 'Bobcorn で生成',
  },
  ko: {
    pageTitle: '아이콘 목록',
    searchPlaceholder: '아이콘 검색...',
    iconCount: '아이콘 {n}개',
    allGroups: '전체',
    noIcons: '이 그룹에 아이콘이 없습니다',
    copyCode: '복사',
    downloadSvg: 'SVG',
    toastCopied: '복사됨: {code}',
    toastDownloaded: '다운로드됨: {name}.svg',
    usageLabel: '개발 참조',
    usageTitle: '프로젝트에서 아이콘 사용하기',
    usageDesc: '3가지 통합 방법 중 선택하세요. 모든 파일이 내보내기에 포함되어 있습니다.',
    unicodeStep1: '1단계 — 폰트 선언',
    unicodeStep2: '2단계 — 기본 클래스 정의',
    unicodeStep3: '3단계 — HTML 엔티티로 사용',
    fontclassStep1: '1단계 — 스타일시트 포함',
    fontclassStep2: '2단계 — 클래스명 사용',
    symbolStep1: '1단계 — JS 스프라이트 포함',
    symbolStep2: '2단계 — 기본 스타일 추가',
    symbolStep3: '3단계 — ID로 참조',
    wikiLinkText: 'Bobcorn Wiki에서 자세히 보기',
    footerGenerated: 'Bobcorn으로 생성됨',
  },
};

/** Wiki language map — matches WIKI_LANG_MAP in ExportDialog */
const WIKI_LANG_MAP: Record<string, string> = {
  'zh-CN': 'zh-CN',
  ja: 'ja',
  ko: 'ko',
  fr: 'fr',
  de: 'de',
  es: 'es',
  'pt-BR': 'pt-BR',
  it: 'it',
  nl: 'nl',
  ru: 'ru',
  tr: 'tr',
  ar: 'ar',
  th: 'th',
  vi: 'vi',
  id: 'id',
};

function getDemoStrings(lang: string): Record<string, string> {
  return DEMO_STRINGS[lang] || DEMO_STRINGS.en;
}

function getWikiLang(lang: string): string {
  return WIKI_LANG_MAP[lang] || 'en';
}

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

// Generate demo page HTML
// woff2Base64: woff2 font base64 encoded, embedded in HTML for file:// support
export const demoHTMLGenerator = (
  groups: DemoGroupData[],
  icons: DemoIconData[],
  woff2Base64?: string,
  config?: {
    hasSymbol: boolean;
    selectedFormats: Record<string, boolean>;
    /** Inline SVG symbol sprite JS — injected directly for preview (no external file) */
    inlineSymbolSprite?: string;
  }
): string => {
  // Replace icon placeholder with the pre-cached base64 data URI (works in standalone HTML)
  const templateWithIcon = htmlTemplate.replace(/APP_ICON_PLACEHOLDER/g, _appIconDataUri);

  const parser = new DOMParser();
  const pageTemplate = parser.parseFromString(templateWithIcon, 'text/html');
  const iconsContainer = pageTemplate.querySelector('[content=icons]')!;
  const fontLine = woff2Base64 ? `var fontBase64 = "${woff2Base64}";` : '';
  const projectName = db.getProjectName();
  const exportConfigLine = config
    ? `var exportConfig = ${JSON.stringify({ hasSymbol: config.hasSymbol, selectedFormats: config.selectedFormats })};`
    : '';

  // Inject localized UI strings for the demo page
  const lang = i18n.language || 'en';
  const uiStrings = getDemoStrings(lang);
  const wikiLang = getWikiLang(lang);
  const wikiBase = `https://bobcorn.caldis.me/wiki/${wikiLang}/`;

  // When inline sprite is provided (preview mode), default to Symbol tab
  const defaultTabLine = config?.inlineSymbolSprite ? 'var defaultTab = "symbol";' : '';

  iconsContainer.innerHTML = `
		var projectName = ${JSON.stringify(projectName)}
		var groups = ${JSON.stringify(groups)};
		var icons = ${JSON.stringify(icons)};
		${fontLine}
		${exportConfigLine}
		var uiStrings = ${JSON.stringify(uiStrings)};
		var wikiBase = ${JSON.stringify(wikiBase)};
		${defaultTabLine}
	`;
  // Preload symbol SVG sprite
  const symbolPreload = pageTemplate.querySelector('[content=symbolPreload]');
  if (symbolPreload) {
    if (config?.inlineSymbolSprite) {
      // Preview mode: inject sprite inline so icons render without external files
      symbolPreload.removeAttribute('src');
      symbolPreload.textContent = config.inlineSymbolSprite;
    } else if (config?.hasSymbol !== false) {
      symbolPreload.setAttribute('src', `./${projectName}.js`);
    } else {
      symbolPreload.removeAttribute('src');
    }
  }

  // Set html lang attribute
  const htmlEl = pageTemplate.querySelector('html');
  if (htmlEl) {
    htmlEl.setAttribute('lang', lang);
  }

  return pageTemplate.querySelector('html')!.outerHTML;
};

// 生成模板CSS文件以供界面引用
// 根据选定的字体格式动态构建 @font-face src
export const iconfontCSSGenerator = (
  icons: DemoIconData[],
  formats?: { woff2?: boolean; ttf?: boolean; woff?: boolean; eot?: boolean }
): string => {
  const projectName = db.getProjectName();
  const fmt = formats || { woff2: true, ttf: true, woff: true, eot: true };

  // Build dynamic @font-face src
  const srcParts: string[] = [];
  if (fmt.eot) srcParts.push(`url('${projectName}.eot?#iefix') format('embedded-opentype')`);
  srcParts.push(`url('${projectName}.woff2') format('woff2')`);
  if (fmt.woff) srcParts.push(`url('${projectName}.woff') format('woff')`);
  srcParts.push(`url('${projectName}.ttf') format('truetype')`);

  const fontFace = `@font-face {\n  font-family: "${projectName}";\n  src: ${srcParts.join(',\n       ')};\n  font-weight: normal;\n  font-style: normal;\n}\n`;
  const baseClass = `.${projectName} {\n  font-family: "${projectName}" !important;\n  font-style: normal;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n`;

  const parts: string[] = [fontFace, baseClass];
  for (let i = 0; i < icons.length; i++) {
    const code = icons[i].iconCode.toLowerCase();
    parts.push(`.${projectName}-${code}:before { content: "\\${code}"; }`);
  }
  return parts.join('\n');
};

// viewBox 正则提取 — 避免每个图标都 new DOMParser()
const VIEWBOX_RE = /viewBox\s*=\s*["']([^"']+)["']/i;
// SVG 内部内容提取
const SVG_INNER_RE = /<svg[^>]*?>([\s\S]*?)<\/svg>/i;
// 引号标准化
const QUOTE_RE = /[\u2018\u2019\u201C\u201D']/g;

// 生成模板Symbol的JS文件以供界面引用
// 优化: regex 提取 viewBox (不用 DOMParser) + array.join
export const iconfontSymbolGenerator = (icons: DemoIconData[]): string => {
  const projectName = db.getProjectName();
  const parts: string[] = new Array(icons.length);

  for (let i = 0; i < icons.length; i++) {
    const icon = icons[i];
    // Flatten <use> references to avoid ID collisions in the SVG sprite.
    // Design tools (Sketch/Figma) export paths in <defs> referenced via <use>,
    // but all icons sharing id="path-1" causes cross-references in a single sprite.
    const content = flattenSvgUseRefs(icon.iconContent);

    // 用 regex 提取 viewBox，避免 DOMParser 开销
    const vbMatch = VIEWBOX_RE.exec(content);
    const viewBox = vbMatch ? vbMatch[1] : '0 0 1024 1024';

    // 提取 <svg> 内部内容
    const innerMatch = SVG_INNER_RE.exec(content);
    const inner = innerMatch ? innerMatch[1] : content;

    // 标准化引号
    const normalized = inner.replace(QUOTE_RE, '"');

    parts[i] =
      `<symbol id="${projectName}-${icon.iconCode}" viewBox="${viewBox}">${normalized}</symbol>`;
  }

  return jsHead + parts.join('') + jsTail;
};
