#!/usr/bin/env node
/**
 * SF Symbols Fixture Generator
 *
 * Generates an .icp (SQLite binary) database from a directory of SF Symbol SVGs
 * and categories.json mapping.
 *
 * Data sources:
 *   - SVGs: generated by `npx sf-symbols-svg` (MoOx/sf-symbols-svg, MIT)
 *   - Categories: extracted from Rspoon3/SFSymbols (MIT) Swift metadata
 *
 * Usage:
 *   node test/fixtures/sf-symbols/generate-icp.js --svg-dir <path-to-svgs>
 *
 * If --svg-dir is omitted, reads SVG content from an existing sf-symbols.icp.
 *
 * Output:
 *   test/fixtures/sf-symbols/sf-symbols.icp
 */

const initSqlJs = require('sql.js/dist/sql-asm.js');
const { writeFileSync, readFileSync, readdirSync, existsSync } = require('fs');
const { join } = require('path');

// ── Constants ─────────────────────────────────────────────────────────────────
const PUA_START = 0xE000;

const categories = JSON.parse(
  readFileSync(join(__dirname, 'categories.json'), 'utf-8')
);

function generateUUID() {
  let d = Date.now();
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (d + Math.random() * 16) % 16 | 0;
    d = Math.floor(d / 16);
    return (c === 'x' ? r : (r & 0x7) | 0x8).toString(16);
  });
}

// ── Main ──────────────────────────────────────────────────────────────────────
async function main() {
  // Parse --svg-dir argument
  const svgDirIdx = process.argv.indexOf('--svg-dir');
  const svgDir = svgDirIdx !== -1 ? process.argv[svgDirIdx + 1] : null;

  if (svgDir && !existsSync(svgDir)) {
    console.error(`SVG directory not found: ${svgDir}`);
    process.exit(1);
  }

  // Load SVG content source
  let getSvg;
  if (svgDir) {
    // Read from SVG files directory
    console.log(`Reading SVGs from: ${svgDir}`);
    getSvg = (name) => {
      const fp = join(svgDir, `${name}.svg`);
      try { return readFileSync(fp, 'utf-8'); } catch { return null; }
    };
  } else {
    // Read from existing .icp
    const icpPath = join(__dirname, 'sf-symbols.icp');
    if (!existsSync(icpPath)) {
      console.error('No --svg-dir and no existing sf-symbols.icp. Provide SVG source.');
      process.exit(1);
    }
    console.log(`Reading SVGs from existing: ${icpPath}`);
    const SQL = await initSqlJs();
    const oldDb = new SQL.Database(new Uint8Array(readFileSync(icpPath)));
    const rows = oldDb.exec('SELECT iconName, iconContent FROM iconData');
    const svgMap = new Map();
    if (rows.length > 0) {
      rows[0].values.forEach(([name, content]) => svgMap.set(name, content));
    }
    oldDb.close();
    getSvg = (name) => svgMap.get(name) || null;
  }

  // Build new database
  const SQL = await initSqlJs();
  const db = new SQL.Database();

  db.run(`CREATE TABLE projectAttributes (id varchar(255), projectName varchar(255), createTime datetime DEFAULT CURRENT_TIMESTAMP, updateTime datetime DEFAULT CURRENT_TIMESTAMP)`);
  db.run(`CREATE TRIGGER projectAttributesTimeRenewTrigger AFTER UPDATE ON projectAttributes FOR EACH ROW BEGIN UPDATE projectAttributes SET updateTime = CURRENT_TIMESTAMP WHERE id = OLD.id; END`);
  db.run(`INSERT INTO projectAttributes (id, projectName) VALUES ('projectAttributes', 'sf-symbols')`);

  db.run(`CREATE TABLE groupData (id varchar(255), groupName varchar(255), groupOrder int(255), groupColor varchar(255), createTime datetime DEFAULT CURRENT_TIMESTAMP, updateTime datetime DEFAULT CURRENT_TIMESTAMP)`);
  db.run(`CREATE TRIGGER groupDataTimeRenewTrigger AFTER UPDATE ON groupData FOR EACH ROW BEGIN UPDATE groupData SET updateTime = CURRENT_TIMESTAMP WHERE id = OLD.id; END`);

  db.run(`CREATE TABLE iconData (id varchar(255), iconCode varchar(255), iconName varchar(255), iconGroup varchar(255), iconSize int(255), iconType varchar(255), iconContent TEXT, iconContentOriginal TEXT, createTime datetime DEFAULT CURRENT_TIMESTAMP, updateTime datetime DEFAULT CURRENT_TIMESTAMP)`);
  db.run(`CREATE TRIGGER iconDataTimeRenewTrigger AFTER UPDATE ON iconData FOR EACH ROW BEGIN UPDATE iconData SET updateTime = CURRENT_TIMESTAMP WHERE id = OLD.id; END`);

  const insG = db.prepare('INSERT INTO groupData (id, groupName, groupOrder, groupColor) VALUES (?, ?, ?, ?)');
  const insI = db.prepare('INSERT INTO iconData (id, iconCode, iconName, iconGroup, iconSize, iconType, iconContent, iconContentOriginal) VALUES (?, ?, ?, ?, ?, ?, ?, ?)');

  let code = PUA_START;
  let totalIcons = 0;
  let skipped = 0;
  const sortedCats = Object.keys(categories).sort();

  sortedCats.forEach((cat, order) => {
    const gid = generateUUID();
    insG.run([gid, cat, order, '']);

    for (const name of categories[cat]) {
      const svg = getSvg(name);
      if (!svg) { skipped++; continue; }
      insI.run([
        generateUUID(),
        code.toString(16).toUpperCase(),
        name,
        gid,
        Buffer.byteLength(svg, 'utf-8'),
        'svg',
        svg,
        svg,
      ]);
      code++;
      totalIcons++;
    }
  });

  insG.free();
  insI.free();

  const data = db.export();
  const icpPath = join(__dirname, 'sf-symbols.icp');
  writeFileSync(icpPath, Buffer.from(data));
  db.close();

  // Summary
  const mb = (Buffer.from(data).length / 1024 / 1024).toFixed(1);
  console.log(`\n=== SF Symbols Fixture Generated ===\n`);
  console.log(`  Groups:   ${sortedCats.length}`);
  console.log(`  Icons:    ${totalIcons}`);
  console.log(`  Skipped:  ${skipped}`);
  console.log(`  PUA:      E000 – ${(code - 1).toString(16).toUpperCase()}`);
  console.log(`  Size:     ${mb} MB`);
  console.log(`  Output:   ${icpPath}\n`);

  sortedCats.forEach((cat) => {
    console.log(`  ${cat.padEnd(24)} ${categories[cat].length} icons`);
  });
  console.log('');
}

main().catch((err) => {
  console.error('Generator failed:', err);
  process.exit(1);
});
