/**
 * SF Symbols Test Fixture — Category Definitions
 *
 * Loads the category→icon mapping extracted from Rspoon3/SFSymbols (MIT).
 * SVGs generated by MoOx/sf-symbols-svg (MIT) from Apple SF Pro Text font.
 *
 * categories.json: { categoryName: [iconName, ...], ... }
 * sf-symbols.icp:  SQLite binary with 28 groups × 7007 icons total
 */

const { readFileSync } = require('fs');
const { join } = require('path');

const categories = JSON.parse(
  readFileSync(join(__dirname, 'categories.json'), 'utf-8')
);

// Sorted category names
const categoryNames = Object.keys(categories).sort();

// Total icon count
const totalIcons = Object.values(categories).reduce((sum, icons) => sum + icons.length, 0);

module.exports = { categories, categoryNames, totalIcons };
